### ISSUE TITLE
Small problem with margins

### ISSUE THREAD

**Issue by stewartobert** [mattnish/rad#2]
First off I would like to say thanks. I've been working on a responsive design for something for a few days now and was starting to integrate the ads in and was surprised to see Google had no method available to dealing with that. Your plugin works quite well.

I found one little problem. I'm using a highly modified version of Bootstrap and the span# tags have margins set. The plugin didn't take into account margins so the result was the ad was the width of the margin wider than the span# block. I made this modification:

Directly below line 62 (var pWidth = this.adParent.width();)

I added this:

pWidth -= (parseInt(this.adParent.parent().css('marginLeft').replace('px', '')) + parseInt(this.adParent.parent().css('marginRight').replace('px', '')));

This seems to have done the trick resulting in the ad being sized correctly.

Thanks once again for the plugin.

Stewart

**Comment by mattnish** [comment]
Hey Stewart, glad the plugin's been helpful to your project.  Yeah, their team is still figuring it out.

I don't have time right now, but I'll take a look in the next few days and test it before adding to the master.  Makes sense though.

Thanks for the issue/fix!

**Comment by mattnish** [comment]
Cool, I've added it to master.  Thanks again for the contribution.
